FROM node:12
WORKDIR /nuxt-student-staging
COPY . .
RUN echo basePath="/student/" >> .env
RUN echo basePathBuild="/student/_nuxt/" >> .env
RUN echo baseUrl="https://staging.petraverse.id/api" >> .env
RUN echo siteKey="6LdoQc0hAAAAAGR-9qVX_HhmGCarOmz9f419FesP" >> .env
# COPY .env .
#COPY .env-dev .env
RUN cat .env
RUN npm install
RUN npm run build
RUN npm run generate

EXPOSE 5000
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=5000
CMD ["npm", "start"]
